### ISSUE TITLE
Улучшения иконки в трее

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#10]
Будут ли улучшения отображения иконки в трее?
А то у меня она выделяется из других иконок трея:
http://img843.imageshack.us/img843/9960/trayicon.png

**Comment by tulskiy** [comment]
я так понял правые скриншоты с КДЕ, левый из винды семерки? проверь что в настройках цветов выключены Tray Background.

**Comment by tulskiy** [comment]
подтверждаю корявость иконки на семерке. надо будет по пикселам править.

**Comment by SD-Leo** [comment]
Прошу прощения, что сразу не пояснил.
Левый - да, из семерки. Tray Background выключены.
Оба правых из GNOME. Верхнее изображение это апплет "notification area" из Avant Windows Navigator. TB тоже выключены. У awn свои темы.
Правый нижний - это станадртный Гном. Тема New Wave. Цвета бекграудов подогнал как сказано в help.

**Comment by tulskiy** [comment]
насколько я знаю в гноме запрос на размер иконки возвращает всегда 24х24и нижняя часть для больших панелей не закрашивается, поэтому фикс будет навряд ли, для остального нужно перерисовывать иконки.

**Comment by SD-Leo** [comment]
ясно...
