### ISSUE TITLE
Вылетает плеер

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#11]
Вылетает плеер при попытке открыть содержащую трек папку.
Версия плеера та, которая распространяется в бинарном виде 0.2
Если плеер просто запустить - папка откроется. После нажатия play, при попытке открыть - вылетает, даже если потом нажать stop.

**Comment by tulskiy** [comment]
запусти плеер из консоли и покажи что выводится

**Comment by SD-Leo** [comment]
leo@Virus:~/musique$ ./musique.sh 
Assertion 'pa_atomic_load(&(b)->_ref) > 0' failed at pulsecore/memblock.c:589, function pa_memblock_unref(). Aborting.
java: pthread_mutex_lock.c:321: __pthread_mutex_lock_full: Assertion `robust || (oldval & 0x40000000) == 0' failed.
Aborted
leo@Virus:~/musique$

**Comment by SD-Leo** [comment]
Кстати, когда из исходников собираю - собирается успешно, а при запуске пишет:
Failed to load Main-Class manifest attribute from musique.jar
Собираю: Apache Ant version 1.8.0 compiled on May 9 2010

**Comment by tulskiy** [comment]
мдя, на винде эта опция тоже фигню какую-то выводит, придется отключить.

**Comment by SD-Leo** [comment]
Ну в прошлых же версиях нормально работало :(. Хорошая функция.

**Comment by tulskiy** [comment]
мы точно про одно и тоже говорим? я эту функцию три дня назад добавил.

**Comment by SD-Leo** [comment]
Я говорю про функцию Open containing folder.

**Comment by tulskiy** [comment]
ну и я про нее же, она особо не тестилась, да и работает некорректно. жаль.

**Comment by SD-Leo** [comment]
Мне казалось она давно уже. Вот и я говорю, что жаль если ее не будет... :(
