### ISSUE TITLE
Контекстное меню в новом плейлисте

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#12]
Как насчет добавления контекстного меню с пунктами: Add Files, Add Folders, Add Location в пустом плейлисте. А то уже несколько раз натыкался: создашь плейлист и по пустому полю правой клавишей тыкаю, чтобы в меню не лезть...

**Comment by tulskiy** [comment]
Сделаем. Там, правда, костыль вставить придется, но это уже мой косяк в проектировании.

**Comment by SD-Leo** [comment]
Ждем... (случайно закрыл :( )
