### ISSUE TITLE
Порядок после dead item

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#14]
Если кликнуть по dead item - сразу произойдет переход к следующему треку. И если нажать Previous, то переход к треку, который играл до dead item не произойдет, а лишь трек начнет играть сначала. Хотелось бы, чтобы переход работал :) Возможно?

**Comment by tulskiy** [comment]
Обработка несуществующих файлов это исключительный случай. Не хотелось бы навешивать туда дополнительную логику.
