### ISSUE TITLE
View Playback Queue

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#15]
Пункт Clear Playback Queue есть, а можно добавить пункт View Playback Queue? Или кнопку: нажал кнопку(галочку) - в плейлисте остались только треки из очереди, еще раз - назад все песенки вернулись. Ну или в pop-up окне вывести список очереди.

**Comment by SD-Leo** [comment]
И еще добавить в окно поиска столбец, в котором бы показывался номер в очереди, если трек в стоит в очереди.

**Comment by xtreye** [comment]
Номер в очереди - мастхэв.

**Comment by tulskiy** [comment]
added Playback Queue Viewer
closed by 97d86232e2d2561e884ea1d96281ff1a31bf1ec7
