### ISSUE TITLE
Запуск трека из окна поиска

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#16]
Было бы неплохо добавить комбинацию (что-нибудь типа Ctrl+Enter) для запуска трека из окна поиска и чтобы при этом окно поиска закрывалось. А то сейчас нашел песню, запустил ее Enter-ом и еще надо закрыть оно поиска. Ну и просто запуск по Enter-у оставить.

**Comment by tulskiy** [comment]
added shift+Enter hotkey in Search Dialog to play selected song and close the dialog. closed by 43898ecdb1f7d5615e7dfcb5971f1e4c91b9ea6b
