### ISSUE TITLE
Ссылка в ReadMe

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#17]
http://forums.sun.com/thread.jspa?threadID=585358
Ссылка уже не действительна :(

**Comment by tulskiy** [comment]
ну что могу сказать, оракл мастдай :)

**Comment by tulskiy** [comment]
fixed broken link to a thread to fix double-click speed on linux. closed by 7cbafbaee25570492bc672d2ad85e33862f2196b
