### ISSUE TITLE
Рандом по папкам

### ISSUE THREAD

**Issue by xtreye** [tulskiy/musique#18]
Сабж - одна из полезнейших функций фубара для меня! 

Очень нужна в двух случаях:
1) В коллекции накиданы файлы с частично заполненными тэгами (при этом они хорошо структурированы по папкам). Ну иногда лень их прописывать прям сейчас, особенно если вообще рандомайзишься по свежевыкачанной помойке.
2) В коллекции куча сборников (самопальных), у каждого трека в таком "сборнике" скорее всего разный альбом, однако лежат они в одной папке. Как пробежаться по разным сборникам? Никак, если нет такого режима

Было бы неплохо иметь рандом по папкам и в musique :)

**Comment by tulskiy** [comment]
ок, только можешь поподробнее описать в каком случае прыгать на новую папку: если следующий трек из другой папки или если ниже по списку нет трэков из той же папки?

**Comment by xtreye** [comment]
как я успел заметить, в том же фубаре выборка из папок ведётся нерекурсивно - каждая папка сама по себе, а когда заканчиваются треки в ней - прыгаем рандомно

**Comment by xtreye** [comment]
а ещё можно рандомайзить по группам - по тому, как их плеер выстраивает в плейлисте - так даже универсальней (особенно если использовать хитрую группировку по паттернам)! killer feature! :)

**Comment by tulskiy** [comment]
Я изначально и задумывал сделать шафл и повтор по паттерну, Repeat Album так и сделан, только паттерн пока не настраиваемый. Посмотрю как это удобнее в интерфейс прикрутить.

**Comment by xtreye** [comment]
Ну изначально так можно просто Random by Group сделать, это ведь не требует никаких интерфейсных ухищрений. Т. е. фактически использовать тот же паттерн, а не отдельный. Кроме простоты реализации (я так понял функционал почти реализован), будет простота для пользователя - не каждый ведь догадается паттерн писать. А функция вполне очевидна - раз есть такое понятие, как "группа", то чего бы и по ним тоже не попрыгать?

Отдельный паттерн тоже может пригодиться - выбока по годам, жанру (хотя тут сложнее, дюже их много, придётся древовидный классификатор заводить), это бы тоже было классно!

**Comment by tulskiy** [comment]
added Repeat / Shuffle Groups and Repeat / Shuffle Albums with adjustable pattern for albums
closed by 33f22cf81341c958e516a5ad7be71ca323571dd0
