### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#3]
Thanks for cool player.
How about new features:
- display/close to tray
- view playlists in tab (no tab if one playlist)
- about information
- global shortcuts
- Drag`n`Drop
- Add directory with music (Not only files)
- Change main icon

**Comment by tulskiy** [comment]
Hi, thanks for your comments.

Display/Close to tray, playlist tabs, drag'n'drop, and a new icon are already implemented in the latest trunk version. You can download source code and compile it to have these and many more new features (see commit log for details). You just need a jdk and ant.

I'm still thinking about showing no tab if there's only one playlist. There's no built-in functionality so it will require some crutches. About dialog should be in the next release.

Global shortcuts can not be implemented in a cross-platform way using standard java tools. And I wish this player to be 100% java.

I hope to roll out a new release soon - the trunk version is pretty much stable, but I don't have much time to polish everything out.

**Comment by SD-Leo** [comment]
Hi, sorry for request some features, i read commit log after creating issue.
Can`t checkout sources because i work through stupid proxy. Wait new release...

**Comment by tulskiy** [comment]
There's nothing wrong with feature requests :) It's actually great. And there's a button "Download Source" on top of the page - it should download a zip archive of the master branch through your browser's proxy. BTW, proxy support in the player is also coming.

**Comment by SD-Leo** [comment]
I love this player!
I compile source in IDEA, version 0.2 much better.
