### ISSUE TITLE
File Operations does not respect special characters

### ISSUE THREAD

**Issue by bassstorm** [tulskiy/musique#35]
Special characters should be handled accurately.
For example, if "/" character is presented in track title, then extra folder will be created at destination during Move files process.
Would be nice to respect Win limitations as well (maybe optional).

**Comment by tulskiy** [comment]
so I guess I need to strip some punctuation from generated file name. What is 100% safe set of punctuation marks that are allowed on all platforms? I'm thinking _+-=.,(){} are safe, rest should either be removed or replaced with some other character. Am I missing any?

**Comment by bassstorm** [comment]
Next ones are allowed by FAT32:
! # $ % & ' ( ) + - @ ^ _ ` { } ~ , . ; = [ ]
Pretty sure all other filesystems also have no issues with them :)

I'd personally prefer to replace "illegal" character by underscore char ("_").

PS. Unicode chars like "é" or "â" shouldn't be replaced of course.

**Comment by tulskiy** [comment]
ok, so it's easier to remove characters that are not allowed - / \ | : \* ? < > " and wikipedia says that + [ ] are not allowed on fat32. anything else?

**Comment by bassstorm** [comment]
Agree, easier to compile list of not allowed chars.
According to Wiki: "+ , . ; = [ ] They are allowed in long file names only." Long file names supported by any decent Win version, so it's not a problem.
I think final list will be something like:
/ \ | : \* ? < > "
