### ISSUE TITLE
one more feature

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#4]
Will be glad to see in new version:
Button "OK" in help and about dialogs, FolderChooser in "Add Location", when I add new playlist and rightclick on white space call context menu with "add location" and "add files", moving song between playlists(dragndrop or "move/copy to NewPlaylist"),
"shuffle&repeat" item in "order"...

**Comment by tulskiy** [comment]
Add Location is intended for adding URLs of shoutcast radios. I'll see if I can write a descent folder chooser.

You can copy/paste between playlists, I thought about making a "move to playlist" item, but there were some problems. I'll come back to that later.

And what exactly is "shuffle & repeat"?

**Comment by SD-Leo** [comment]
In "shuffle" sequence each song may play one time. When all song have played player to stop. In "shuffle&repeat" sequence each song may play one and more times.
Example, in playlist 4 song: 1, 2, 3 and 4.
shuffle: start -> 1 song -> 4 song -> 2 song -> 3 song -> stop
shuffle&repeat: start -> 1 -> 3 -> 1 -> 2 -> 4 -> 3 -> 1 -> 2 -> ...

**Comment by tulskiy** [comment]
Hmm, currently Shuffle mode is what you describe as shuffle&repeat. Only difference is that songs will be played in the same order every time. There's a Random mode that will play them truly randomly.

Do you want the shuffle mode that will stop when every song is played?

PS. можно по-русски писать.

**Comment by SD-Leo** [comment]
Фуф.. давно хотел спросить про русский, с мои-то английским :)
Тогда к shuffle вопросов нет.
Даже и не сообразил, что Add Location для URL. Еще привык что добавление файлов и директорий отдельные пункты, поэтому не сразу понял, что Add Files это и то и другое сразу...
Когда создаешь новый плэйлист, правой клавишей по пустому месту и вызывается контекстное меню файла(Cut, Copy...), хотя плейлист еще пустой. Так неверное быть не должно...

**Comment by tulskiy** [comment]
В Add Location можно любой адрес вводить, но в основном да, это для URL. 

Насчет добавления файлов и директорий отдельными пунктами - в джаве нет стандартного контрола с деревом папок. Свой я писал, но он не очень красиво выглядит, может когда-нибудь руки и дойдут.

Менюшки подправлю, они динамически делаются, проблем быть не должно.

**Comment by SD-Leo** [comment]
Просто увидел в File Operations пункт Destination. Там есть FolderChooser (это тобой написанный?) и подумал что можно было бы разделить. В принципе и Add Files хватит, так даже универсальнее.
