### ISSUE TITLE
Tag editor: unable to remove ID3v1 field value

### ISSUE THREAD

**Issue by bassstorm** [tulskiy/musique#47]
One tries to clean/remove some field value. Both ID3v2 and ID3v1 tags are presented. ID3v2 is updated successfully, but ID3v1 update fails due to "java.io.IOException: Operation not supported". As result, one sees "removed" tag in Tag Editor again as it is loaded from not updated ID3v1 frame.

**Comment by tulskiy** [comment]
could not reproduce

**Comment by bassstorm** [comment]
Will take a look later today. Maybe depends on file size, flags or something

**Comment by bassstorm** [comment]
Unable to reproduce as well. Closing for now.
