### ISSUE TITLE
OSD

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#5]
Pop-up сообщение (которое возле трея) о проигрываемой песне будет? Здорово если еще можно было бы настраивать что и как там отображать.

Еще было бы неплохо как-то текущее состояние плеера отобразить на кнопках stop, play, pause и в трее иконку соответственно поменять.

Может быть временное отображение прогресса ( 1:34/2:45 ) перенести куда-нибудь после ползунка прокрутки и как-нибудь визуально выделить: шрифт пожирнее.

Где-нибудь бы еще показывалось количество треков в плэйлисте, общая продолжительность, суммарное занимаемое месть на диске...

Локализация? Меня в принципе более чем устраивает английский. Но может быть некоторых пользователей пугает: хотят на родном.

Иконки не во всех формах заменил. В диалоге Add Location подсказку лэйблом вывести: http://bla-bla..., В окне About и Help шрифты при виндовом looknfeel страшные. Будут другие LooknFeel? Альтернатива обложкам.

Minimal view будет?

**Comment by tulskiy** [comment]
Pop-up сообщение в трее пришлось отключить из-за того что это вызывало дэдлок и зависание плеера.

Look n Feel можно менять в настройках, я в основном тестирую на Nimbus и Metal, поведение с другими LaF не гарантирую.

Вшивание локализации это процесс несколько долгий, менять много нужно, так что будет нескоро.

**Comment by SD-Leo** [comment]
Извиняюсь, что в одном сообщении запрашиваю несколько фич, но мне очень интересно.
Как насчет остального, что я перечислил?

**Comment by tulskiy** [comment]
Извиняюсь что долго не отвечал. Работа.

По остальным пунктам.

> Еще было бы неплохо как-то текущее состояние плеера отобразить на кнопках stop, play, pause

что именно отображать? менять иконку плей на паузу?

> Может быть временное отображение прогресса ( 1:34/2:45 ) перенести куда-нибудь после ползунка прокрутки и как-нибудь визуально выделить: шрифт пожирнее.

Почему бы и нет. Добавлю.

> Где-нибудь бы еще показывалось количество треков в плэйлисте, общая продолжительность, суммарное занимаемое месть на диске...

Никогда не понимал зачем это нужно. Посмотрим.

> Minimal view будет?

Скорее всего нет.

**Comment by SD-Leo** [comment]
http://img689.imageshack.us/img689/5922/onpause.jpg  Тут можно сделать так, чтобы отображалась не ссылка, а сразу картинка?
Нет, не менять иконку плей на пауза, а менять иконку паузы на иконку паузы_нажатую, как например нижний вариант на картинке.
Или цветом другим, ну вообщем как нибудь... А в трее, когда контекстное меню вызываешь можно хотя бы галочку напротив текущего состояния.

Суммарное время проигрывания всех композиция я тоже не очень понимаю, а вот количество треков в плейлистам может помочь сориентироваться.

А подсказка в Add Location? А то теряешься что вводить и в каком формате.

Жаль про pop-up сообщения :( Очень бы хотелось эту фишку. Как-то уж очень привыкли к ней.

И еще. Можно когда идет импорт файлов какой-нибудь прогресс бар вывести или хотя бы время прошедшее/оставшееся выводить?
И перенести пункт property в конец меню edit, а то во многих (наверное во всех) этот пункт последний и по привычке ищешь его последним.

**Comment by tulskiy** [comment]
Когда добавляются файлы, выводится диалог в котором показываются какие файлы добавляются. Прогресс бар показать не могу потому как не знаю сколько файлов в папке заранее. Диалог не модальный, поэтому он может свернуться, что, видимо, и произошло.

Пункт Properties перенесу. Подсказку в Add Location добавлю.

Остальное позже/навряд ли.

**Comment by SD-Leo** [comment]
Поправил ссылку на картинку.

**Comment by tulskiy** [comment]
Да, я понял что вы имели в виду. Я набросал такой функционал, но выглядело это некрасиво и я откатил. Разве что только для кнопки паузы такое сделать.

**Comment by SD-Leo** [comment]
Просто хотелось бы иметь способ быстро определять текущее состояние плеера. В идеале бы, взглянув на иконку в трее. Ну и в плеере, чтобы где-нибудь на видном месте.
Все это конечно не принесет огромной пользы, но хорошее мнение зачастую складывается их приятных мелочей...
