### ISSUE TITLE
Tagging: not all fields of Mp4 tag are read

### ISSUE THREAD

**Issue by bassstorm** [tulskiy/musique#52]
Some fields of Mp4 tag are not read. Artist and Album to name a few. Though, the fields are written by Musique and could be seen by 3rd party software (foobar2000, for example). Quick investigation makes me think about encoding issues: (c)ART tag is expected, but <?>ART is actually read from tag. Not sure, just give a start point.

PS. TagTest fails due to this issue.

**Comment by tulskiy** [comment]
I do remember fixing this while migrating to maven, I'll see if it's still present.
