### ISSUE TITLE
Контекстное меню и после удаления

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#6]
Контекстное меню трека проподает, когда вызывается меню 2-го уровня. После вызова контекстного меню опять левым кликом выделяем трек и тогда меню пропадет, еще раз выделим - нормально работает, еще раз - пропадает.
"К сожалению" после перезапуска баг пропадает - отловить сложно. Возможно проблема Look`n`Feel...

После удаления трека с жесткого диска кнопки на панели управления не реагируют, пока трек не запустишь двойным кликом.

Прилагаю видео для большей ясности. 
http://dl.dropbox.com/u/10960746/musique.mp4
PS: не стал создавать два разных тикета, т.к. в видео записал обе ошибки.

**Comment by tulskiy** [comment]
Да, бага с меню есть, причину не знаю. Пытался копаться на джавовых форумах, ничего вразумительного не нашел. Можно обойти если переходить в подменю с клавиатуры.

Второе пофиксил.

**Comment by tulskiy** [comment]
Как часто у вас возникает баг с подменю? Какая у вас платформа и версия джавы?

**Comment by SD-Leo** [comment]
Замечал раза 2-3. Сначала не мог выявить закономерность бага, поэтому записал видео. Использую плеер и на Винде 7 ultimate 32 и на Убунте 10.04 32. На винде баг не замечал, да и виндой пользуюсь не часто. На винде java update 18. 
На Убунте:
leo@virus:~$ java -version
java version "1.6.0_18"
OpenJDK Runtime Environment (IcedTea6 1.8.1) (6b18-1.8.1-0ubuntu1)
OpenJDK Server VM (build 16.0-b13, mixed mode)
Баг замечал только на Nimbus. Сейчас буду пробовать другие. После перезапуска баг пропадает. Возможно надо чтобы плеер поработал какое-то время. Кстати с главным меню тоже это баг был.

**Comment by tulskiy** [comment]
Спасибо большое. Ладно, будем считать что некритично.

**Comment by SD-Leo** [comment]
http://dl.dropbox.com/u/10960746/musique2.mp4
Надеюсь это видео "прольет еще больше света" на баг.
Сначало все хорошо, играет трек, проматываем его - все нормально. Включаем следующий трек, проматываем его - и опа: меню "сломалось" после промотки. Причем даже если включить первый трек все равно не помогает. (LooKnFeel непричем). Перезапуск плеера помогает, но пока опять не начнем промотку.
После перезапуска отображение плейлиста как-то изменяется в худшую сторону :(

**Comment by tulskiy** [comment]
fixed menu glitch after using progress bar, closed by d87c175817938d3c4fe999af64144c856362cf02

**Comment by tulskiy** [comment]
Спасибо большое! Замечательный скилл тестера. Проблема, видимо, была из-за того pop-up окошка что показывается при перемотке.
