### ISSUE TITLE
Двойной клик в плейлисте

### ISSUE THREAD

**Issue by SD-Leo** [tulskiy/musique#9]
Мне кажется или действительно двойной клик в плейлисте плеера надо производить гораздо быстрее чем в системе?

**Comment by tulskiy** [comment]
судя по всему это баг джавы, тут воркараунды для убунты: http://forums.sun.com/thread.jspa?threadID=585358

**Comment by SD-Leo** [comment]
Вроде сработало. Спасибо за ссылку.
